packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
yarnPath: ".yarn/releases/yarn-3.1.1.cjs"
enableImmutableInstalls: false
